### PR TITLE
fp-ts version 2.13.1 update

### PR DESCRIPTION
**Pull request by Sk0voroda**
i will try to update more

### CODE REVIEW

**Comment by grossbart** [comment]
Hi @Sk0voroda – thanks a lot for your effort! I would prefer to not keep the historic version and just update the recipes to the newest version of fp-ts. I think it would be confusing otherwise if people are not aware of the nuances.

Could you update your PR? Also, happy to merge more, thanks!

**Comment by Sk0voroda** [comment]
Hi @grossbart, ok np i will remove old version and update recipes. Thanks

**Comment by Sk0voroda** [comment]
Hi @grossbart i finished changes. Check pls. I extended one of examples if you dont mind :) You can merge it. Maybe better to squash all because i didnt follow any guidelines while making commits. I will try to add more

**Comment by grossbart** [comment]
Thanks a lot, @Sk0voroda! 🙏

**Pull request merged**
